import { FC } from 'react'
import Head from 'next/head'
import { Box, Stack, Text, Image, Center, Button } from '@chakra-ui/react'
import { ExternalLinkIcon } from '@chakra-ui/icons'
import { Layout } from '@dae/ui'

const Home: FC = () => {
  return (
    <>
      <Head>
        <title>Home | DAE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout.Page>
        <Center
          height={{ md: 'calc(100vh - 160px)', base: 'unset' }}
          py={8}
          overflowY={'auto'}
        >
          <Stack
            width={{ md: '80vw', base: '90vw' }}
            maxWidth={{ md: '100vh', base: 'unset' }}
            direction={{ md: 'row', base: 'column' }}
            spacing={{ md: 8, base: 4 }}
          >
            <Center padding={'30px'}>
              <Image src="/dae-home-image.png" borderRadius={'lg'} />
            </Center>
            <Center padding={'30px'}>
              <Stack spacing={8}>
                <Text
                  fontSize={'4xl'}
                  fontWeight={'extrabold'}
                  lineHeight={'normal'}
                >
                  Decentralized Autonomous Education
                </Text>
                <Stack spacing={4} fontSize={'lg'}>
                  <Text>
                    It is an innovative learning model that leverages the
                    principles and applications of Web3.
                  </Text>
                  <Text>
                    An instance of the DAE model, called a class, is made of a
                    group of teachers (at least one), a group of learners (at
                    least two), and a topic to teach and learn.
                  </Text>
                  <Text>
                    The purpose of the model is to maximize the transfer of
                    knowledge about the topic from the teacher to the learners
                    in a homogeneous way, i.e. without many disparities.
                  </Text>
                </Stack>
                <Box mt="8">
                  <Button
                    rightIcon={<ExternalLinkIcon />}
                    variant="outline"
                    onClick={() =>
                      window.open('https://cubiclearn.gitbook.io/', '_blank')
                    }
                  >
                    GitBook
                  </Button>
                </Box>
              </Stack>
            </Center>
          </Stack>
        </Center>
      </Layout.Page>
    </>
  )
}

export default Home
