import Head from 'next/head'
import { CredentialInfoContainer, Layout } from '@dae/ui'
import { Stack } from '@chakra-ui/react'
import { useRouter } from 'next/router'
import { Address } from 'viem'

export default function Info() {
  const router = useRouter()
  const credentialCid = router.query.credentialCid as string
  const courseAddress = router.query.address as Address

  return (
    <>
      <Head>
        <title>Credential Info | DAE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout.Course heading="Credential Info">
        <Stack spacing={4}>
          <CredentialInfoContainer
            credentialCid={credentialCid}
            courseAddress={courseAddress}
          />
        </Stack>
      </Layout.Course>
    </>
  )
}
