import Head from 'next/head'
import { EnrollTeachersForm, Layout } from '@dae/ui'
import { Stack } from '@chakra-ui/react'
import { useRouter } from 'next/router'

export default function ProfilePage() {
  const { query } = useRouter()
  const courseAddress = query.address as string

  return (
    <>
      <Head>
        <title>Teachers | DAE</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout.Course heading='Enroll teacher'>
        <Stack spacing={8}>
          <EnrollTeachersForm courseAddress={courseAddress} />
        </Stack>
      </Layout.Course>
    </>
  )
}
