import Head from 'next/head'
import { Layout, TransferCredentialsFormContainer } from '@dae/ui'
import { Stack } from '@chakra-ui/react'
import { useRouter } from 'next/router'
import { Address } from 'viem'
import withCourseRoleAuth from '../../../../components/HOC/withCourseRole'

function EnrollTeachers() {
  const { query } = useRouter()
  const courseAddress = query.address as Address

  return (
    <>
      <Head>
        <title>Teachers | DAE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout.Course heading="Enroll teacher">
        <Stack spacing={8}>
          <TransferCredentialsFormContainer
            courseAddress={courseAddress}
            credentialType={'MAGISTER'}
          />
        </Stack>
      </Layout.Course>
    </>
  )
}

export default withCourseRoleAuth(EnrollTeachers, 'ADMIN')
