import Head from 'next/head'
import { Layout, TransferCredentialsForm } from '@dae/ui'
import { Stack, Tabs, TabList, Tab, Link } from '@chakra-ui/react'
import NextLink from 'next/link'
import { useRouter } from 'next/router'

export default function ProfilePage() {
  const { query } = useRouter()
  const courseAddress = query.address as string

  return (
    <>
      <Head>
        <title>New Students | DAE</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout.Course heading='Enroll New Students'>
        <Stack spacing={8}>
          <Tabs defaultIndex={1}>
            <TabList>
              <Link
                as={NextLink}
                href={`/course/${courseAddress}/students/list`}
                style={{ textDecoration: 'none' }}
              >
                <Tab>Students List</Tab>
              </Link>
              <Tab>Enroll New Students</Tab>
            </TabList>
          </Tabs>
          <TransferCredentialsForm courseAddress={courseAddress} />
        </Stack>
      </Layout.Course>
    </>
  )
}
