import Head from 'next/head'
import { Layout } from '@dae/ui'
import { Stack, Tabs, TabList, Tab, Link } from '@chakra-ui/react'
import NextLink from 'next/link'
import { useRouter } from 'next/router'
import { CredentialsAirDropForm } from '@dae/ui'
import { useNetwork } from 'wagmi'

export default function ProfilePage() {
  const { query } = useRouter()
  const address = query.address as string | undefined
  const { chain, chains } = useNetwork()

  return (
    <>
      <Head>
        <title>Subscribe New Students</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout.Course heading='Enroll New Students'>
        <Stack spacing={8}>
          <Tabs defaultIndex={1}>
            <TabList>
              <Link
                as={NextLink}
                href={`/course/${address}/students/list?chainId=${
                  chain ? chain.id : chains[0].id
                }`}
                style={{ textDecoration: 'none' }}
              >
                <Tab>Students List</Tab>
              </Link>
              <Tab>Enroll New Students</Tab>
            </TabList>
          </Tabs>
          <CredentialsAirDropForm />
        </Stack>
      </Layout.Course>
    </>
  )
}
