import Head from 'next/head'
import {Layout} from '@dae/ui'
import {Stack, Tabs, TabList, Tab, Link, Center, Spinner, OrderedList, ListItem} from '@chakra-ui/react'
import NextLink from 'next/link'
import {useRouter} from 'next/router'
import {useCourseStudents} from '@dae/hooks'

export default function StudentsList() {
  const {query} = useRouter()
  const address = query.address as string | undefined
  const {data, isLoading} = useCourseStudents(address)

  return (
    <>
      <Head>
        <title>Students List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout.Course heading="Students List">
        <Stack spacing={8}>
          <Tabs defaultIndex={0}>
            <TabList>
              <Tab>Students List</Tab>
              <Link as={NextLink} href={`/course/${address}/students/enroll`} style={{textDecoration: 'none'}}>
                <Tab>Enroll New Students</Tab>
              </Link>
            </TabList>
          </Tabs>
          {!isLoading ? (
            data.students.length > 0 ? (
              <OrderedList>
                {data.students.map((student: any) => {
                  return <ListItem key={student.studentAddress}>{student.studentAddress}</ListItem>
                })}
              </OrderedList>
            ) : (
              <></>
            )
          ) : (
            <Center>
              <Spinner thickness="4px" speed="0.65s" emptyColor="gray.200" color="gray.500" size="xl" />
            </Center>
          )}
        </Stack>
      </Layout.Course>
    </>
  )
}
