import Head from 'next/head'
import { Layout } from '@dae/ui'
import { DashboardContainer } from '@dae/ui'
import { useRouter } from 'next/router'
import { Address } from 'viem'

function Dashboard() {
  const router = useRouter()
  const courseAddress = router.query.address as Address

  return (
    <>
      <Head>
        <title>Dashboard | DAE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout.Course heading="Dashboard">
        <DashboardContainer courseAddress={courseAddress} />
      </Layout.Course>
    </>
  )
}

export default Dashboard
