import Head from 'next/head'
import { Layout, ProposalContainer } from '@dae/ui'
import { useRouter } from 'next/router'
import { ProposalOverview } from '@dae/ui'
import { Address } from 'wagmi'

export default function TransferKarmaPage() {
  const router = useRouter()
  const proposalId = router.query.proposalId as string
  const courseAddress = router.query.address as Address

  return (
    <>
      <Head>
        <title>Proposals | DAE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout.Course heading="Proposal overview">
        <ProposalContainer courseAddress={courseAddress}>
          <ProposalOverview
            proposalId={proposalId}
            courseAddress={courseAddress}
          />
        </ProposalContainer>
      </Layout.Course>
    </>
  )
}
