import Head from 'next/head'
import { Layout } from '@dae/ui'
import { useRouter } from 'next/router'
import { ProposalOverview } from '@dae/ui'

export default function TransferKarmaPage() {
  const router = useRouter()
  const { proposalId } = router.query as { proposalId: string }

  return (
    <>
      <Head>
        <title>Proposals | DAE</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout.Course heading='Proposal overview'>
        <ProposalOverview proposalId={proposalId} />
      </Layout.Course>
    </>
  )
}
