import Head from 'next/head'
import { Layout, ProposalContainer } from '@dae/ui'
import { CreateProposalForm } from '@dae/ui'
import { Address } from 'wagmi'
import { useRouter } from 'next/router'

export default function TransferKarmaPage() {
  const router = useRouter()
  const courseAddress = router.query.address as Address

  return (
    <>
      <Head>
        <title>Proposals | DAE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout.Course heading="Create proposal">
        <ProposalContainer courseAddress={courseAddress}>
          <CreateProposalForm />
        </ProposalContainer>
      </Layout.Course>
    </>
  )
}
