import Head from 'next/head'
import { Layout } from '@dae/ui'
import { useSpaceProposal, useSpaceProposalVotes } from '@dae/snapshot'
import { useRouter } from 'next/router'

export default function TransferKarmaPage() {
  const { query } = useRouter()
  const proposal = query.proposal as string | undefined
  const { data: spaceData, isLoading: isSpaceDataLoading } =
    useSpaceProposal(proposal)
  const { data: spaceVotesData, isLoading: isSpaceVotesDataLoading } =
    useSpaceProposalVotes(proposal)
  console.log(spaceData, spaceVotesData)

  return (
    <>
      <Head>
        <title>Proposals | DAE</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout.Course heading='Transfer Karma'>
        <p>TEST</p>
      </Layout.Course>
    </>
  )
}
