import Head from 'next/head'
import {Layout} from '@dae/ui'

export default function ProfilePage() {
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout.Profile heading="Profile">
        <h1>Profile Page</h1>
      </Layout.Profile>
    </>
  )
}
