import Head from 'next/head'
import {Layout} from '@dae/ui'
import {Box, Heading, Stack, Text, Spinner, Link, Image, Center} from '@chakra-ui/react'
import {useCourse} from '@dae/hooks'
import {useRouter} from 'next/router'
import NextLink from 'next/link'

export default function CoursePage() {
  const {query} = useRouter()
  const address = query.address as string | undefined
  const {data, isLoading} = useCourse(address)

  return (
    <>
      <Head>
        <title>{`Course Info | ${address}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout.Course heading="About the course">
        {!isLoading ? (
          <Stack spacing={4}>
            <Box>
              <Heading as="h2" fontWeight="semibold" fontSize={'xl'}>
                Address:
              </Heading>
              <Text>{address}</Text>
            </Box>
            <Box boxSize="sm">
              <Image src={data.course.image_url} alt="Green double couch with wooden legs" borderRadius="lg" />
            </Box>
            <Box>
              <Heading as="h2" fontWeight="semibold" fontSize={'2xl'}>
                Title:
              </Heading>
              <Text>{data.course.name}</Text>
            </Box>
            <Box>
              <Heading as="h2" fontWeight="semibold" fontSize={'2xl'}>
                Description:
              </Heading>
              <Text>{data.course.description}</Text>
            </Box>
            <Box>
              <Heading as="h3" fontWeight="semibold" fontSize={'2xl'}>
                Social:
              </Heading>
              <Box>
                Website:{' '}
                <Link href={data.course.website_url} as={NextLink} target="_blank">
                  {data.course.website_url}
                </Link>
              </Box>
              <Box>
                Access Link:{' '}
                <Link href={data.course.access_url} as={NextLink} target="_blank">
                  {data.course.access_url}
                </Link>
              </Box>
            </Box>
          </Stack>
        ) : (
          <Center>
            <Spinner thickness="4px" speed="0.65s" emptyColor="gray.200" color="gray.500" size="xl" />
          </Center>
        )}
      </Layout.Course>
    </>
  )
}
