import Head from 'next/head'
import { Layout } from '@dae/ui'
import {
  Box,
  Heading,
  Stack,
  Text,
  Link,
  Image,
  Alert,
  AlertTitle,
  AlertIcon,
  AlertDescription,
  Center,
  Spinner,
} from '@chakra-ui/react'
import { useRouter } from 'next/router'
import NextLink from 'next/link'
import { useCourse } from '@dae/hooks'
import { Address } from 'viem'
import { useNetwork } from 'wagmi'

export default function CoursePage() {
  const router = useRouter()
  const { chain } = useNetwork()

  if (!chain) {
    router.push('/')
  }

  const {
    data: courseData,
    isLoading,
    error,
  } = useCourse(router.query.address as Address, chain!.id)

  return (
    <>
      <Head>
        <title>Course Info | DAE</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout.Course heading='About the course'>
        {error ? (
          <Alert status='error'>
            <AlertIcon />
            <Box>
              <AlertTitle>Error</AlertTitle>
              <AlertDescription>
                There is an error fetching your data. Try again later.
              </AlertDescription>
            </Box>
          </Alert>
        ) : (
          <></>
        )}
        {isLoading || !courseData ? (
          <Center>
            <Spinner />
          </Center>
        ) : (
          <></>
        )}
        {courseData ? (
          <Stack spacing={4}>
            <Box>
              <Heading as='h2' fontWeight='semibold' fontSize={'xl'}>
                Address:
              </Heading>
              <Text>{courseData.address}</Text>
            </Box>
            <Box boxSize='sm'>
              <Image
                src={courseData.image_url}
                alt='Green double couch with wooden legs'
                borderRadius='lg'
              />
            </Box>
            <Box>
              <Heading as='h2' fontWeight='semibold' fontSize={'2xl'}>
                Title:
              </Heading>
              <Text>{courseData.name}</Text>
            </Box>
            <Box>
              <Heading as='h2' fontWeight='semibold' fontSize={'2xl'}>
                Description:
              </Heading>
              <Text>{courseData.description}</Text>
            </Box>
            <Box>
              <Heading as='h3' fontWeight='semibold' fontSize={'2xl'}>
                Social:
              </Heading>
              <Box>
                Website:{' '}
                <Link
                  href={courseData.website_url}
                  as={NextLink}
                  target='_blank'
                >
                  {courseData.website_url}
                </Link>
              </Box>
              <Box>
                Access Link:{' '}
                <Link
                  href={courseData.access_url}
                  as={NextLink}
                  target='_blank'
                >
                  {courseData.access_url}
                </Link>
              </Box>
            </Box>
          </Stack>
        ) : (
          <></>
        )}
      </Layout.Course>
    </>
  )
}
