import Head from 'next/head'
import { Layout } from '@dae/ui'
import { CourseInfo } from '@dae/ui'

function CourseSummary() {
  return (
    <>
      <Head>
        <title>Course Info | DAE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout.Course heading="About the course">
        <CourseInfo />
      </Layout.Course>
    </>
  )
}

export default CourseSummary
