import Head from 'next/head'
import { Layout } from '@dae/ui'
import { KarmaRatingContainer } from '@dae/ui'
import { useAccount } from 'wagmi'

export default function TransferKarmaPage() {
  const { address } = useAccount()

  return (
    <>
      <Head>
        <title>My Karma | DAE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout.Course heading="My Karma">
        <KarmaRatingContainer userAddress={address} />
      </Layout.Course>
    </>
  )
}
