import Head from 'next/head'
import { Layout } from '@dae/ui'
import { KarmaTransferForm } from '@dae/ui'
import { useRouter } from 'next/router'
import { Address, useNetwork } from 'wagmi'
import { DefaultChain } from '@dae/chains'

export default function TransferKarmaPage() {
  const { query } = useRouter()
  const { chain } = useNetwork()

  return (
    <>
      <Head>
        <title>Subscribe New Students</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout.Course heading='Transfer Karma'>
        <KarmaTransferForm
          courseAddress={query!.address as Address}
          chainId={chain ? chain.id : DefaultChain.id}
        />
      </Layout.Course>
    </>
  )
}
