import Head from 'next/head'
import { Layout } from '@dae/ui'
import { Stack } from '@chakra-ui/react'
import { CreateCourseForm } from '@dae/ui'

export default function AddCoursePage() {
  return (
    <>
      <Head>
        <title>Create Course | DAE</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout.Profile heading='Create new course'>
        <Stack spacing={8}>
          <CreateCourseForm />
        </Stack>
      </Layout.Profile>
    </>
  )
}
