import Head from 'next/head'
import { Layout } from '@dae/ui'
import { Stack, Tabs, TabList, Tab } from '@chakra-ui/react'
import { CustomLink } from '@dae/ui'
import { CourseCardList } from '@dae/ui'

export default function Partecipating() {
  return (
    <>
      <Head>
        <title>Student Courses | DAE</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout.Profile heading='Partecipating'>
        <Stack spacing={8}>
          <Tabs defaultIndex={1}>
            <TabList>
              <CustomLink href='/profile/courses/teaching'>
                <Tab>Teaching</Tab>
              </CustomLink>
              <Tab>Partecipating</Tab>
              <CustomLink href='/profile/courses/create'>
                <Tab>Create</Tab>
              </CustomLink>
            </TabList>
          </Tabs>
          <CourseCardList isMagister={false} />
        </Stack>
      </Layout.Profile>
    </>
  )
}
