import Head from 'next/head'
import {useTeacherCourses} from '@dae/hooks'
import {Layout} from '@dae/ui'
import NextLink from 'next/link'
import {CourseCard} from '@dae/ui'
import {SimpleGrid, Stack, Spinner, Tabs, TabList, Tab, Link, Center} from '@chakra-ui/react'

export default function AddCoursePage() {
  const {isLoading, data} = useTeacherCourses()

  return (
    <>
      <Head>
        <title>My courses</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout.Profile heading="Teaching">
        <Stack spacing={8}>
          <Tabs defaultIndex={0}>
            <TabList>
              <Tab>Teaching</Tab>
              <Link as={NextLink} href="/profile/courses/partecipating" style={{textDecoration: 'none'}}>
                <Tab>Partecipating</Tab>
              </Link>
              <Link as={NextLink} href="/profile/courses/create" style={{textDecoration: 'none'}}>
                <Tab>Create</Tab>
              </Link>
            </TabList>
          </Tabs>
          {!isLoading ? (
            <SimpleGrid columns={{sm: 1, md: 2, lg: 3, xl: 4}} spacing={8}>
              {data.courses.map((course: any) => {
                return <CourseCard address={course.address} key={course.address} />
              })}
            </SimpleGrid>
          ) : (
            <Center>
              <Spinner thickness="4px" speed="0.65s" emptyColor="gray.200" color="gray.500" size="xl" />
            </Center>
          )}
        </Stack>
      </Layout.Profile>
    </>
  )
}
