import Head from 'next/head'
import {Layout} from '@dae/ui'
import NextLink from 'next/link'
import {CourseCard} from '@dae/ui'
import {SimpleGrid, Stack, Spinner, Tabs, TabList, Tab, Link, Center} from '@chakra-ui/react'
import {GetServerSideProps} from 'next'

export default function AddCoursePage({courses}: {courses: any[]}) {
  return (
    <>
      <Head>
        <title>My courses</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout.Profile heading="Teaching">
        <Stack spacing={8}>
          <Tabs defaultIndex={0}>
            <TabList>
              <Tab>Teaching</Tab>
              <Link as={NextLink} href="/profile/courses/partecipating" style={{textDecoration: 'none'}}>
                <Tab>Partecipating</Tab>
              </Link>
              <Link as={NextLink} href="/profile/courses/create" style={{textDecoration: 'none'}}>
                <Tab>Create</Tab>
              </Link>
            </TabList>
          </Tabs>
          {courses.length == 0 ? (
            <p>No courses</p>
          ) : (
            <SimpleGrid columns={{sm: 1, md: 2, lg: 3, xl: 4}} spacing={8}>
              {courses.map((course: any) => {
                return <CourseCard address={course.address} key={course.address} />
              })}
            </SimpleGrid>
          )}
        </Stack>
      </Layout.Profile>
    </>
  )
}

export const getServerSideProps: GetServerSideProps<{courses: any[]}> = async (context) => {
  const {chainId} = context.query as {address: string; chainId: string}

  if (!chainId) {
    return {
      redirect: {
        permanent: false,
        destination: `/profile`,
      },
      props: {},
    }
  }

  const res = await fetch(`${process.env.API_URL}teacher/courses?chainId=${chainId}`, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
      cookie: context.req.headers.cookie! || '',
    },
  })

  if (!res.ok) {
    return {
      props: {
        courses: [],
      },
    }
  }

  const json = await res.json()

  return {
    props: {
      courses: json,
    },
  }
}
