name: CI

on:
  push:

jobs:
  build:
    name: Check and Build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    # To use Remote Caching, uncomment the next lines and follow the steps below.
    # env:
    #  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    #  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set commit SHA
        id: commit_sha
        run: |
          echo "NEXT_PUBLIC_COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Set commit tag (if it exists)
        id: tag
        run: |
          TAG=$(git describe --tags --abbrev=0 --exact-match 2>/dev/null || true)
          if [ -n "$TAG" ]; then
            echo "NEXT_PUBLIC_COMMIT_TAG=$TAG" >> $GITHUB_ENV
          fi

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.6.5

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Check
        run: pnpm check
        env:
          NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID }}

      - name: Lint
        run: pnpm lint
